name: filcnaplo
description: "Nem hivatalos e-napló alkalmazás az e-Kréta rendszerhez"
version: 2.1.3+64
publish_to: none

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.1
  cupertino_icons: ^1.0.2
  dynamic_theme:
    git: 
      url: https://github.com/Norbert515/dynamic_theme
  feather_icons_flutter: ^4.7.4
  flutter_typeahead: ^2.0.0
  file_picker: ^2.1.6
  package_info: ^2.0.0
  intl: ^0.17.0
  flutter_linkify: #TODO return to main pub as soon as his PR is merged
    git:
      url: https://github.com/MohamedEL-Torky/flutter_linkify
  url_launcher: ^5.4.10
  flutter_html: ^1.0.0
  share: any
  sqflite: ^2.0.0+3
  permission_handler: ^5.0.0
  path_provider: ^2.0.1
  tinycolor: ^1.0.2
  open_file: ^3.0.1
  background_fetch: ^0.7.0
  circular_reveal_animation: ^2.0.0
  flutter_speed_dial:
    git:
      url: https://github.com/irasekh3/flutter_speed_dial
      ref: master
  image_cropper: ^1.2.3
  fl_chart: ^0.20.1
  flutter_material_color_picker: ^1.0.5
  flutter_swiper: ^1.1.6
  in_app_review: ^1.0.4
  pdf: ^3.0.1
  printing: ^5.0.0
  photo_view: ^0.11.1
  downloads_path_provider: ^0.1.0
  webview_flutter: any
  flutter_staggered_animations:
    git:
      url: https://github.com/josh-burton/flutter_staggered_animations.git
      ref: findAncestorWidgetOfExactType
  flutter_web_browser: ^0.14.0
  sliding_sheet: ^0.5.0

#dev_dependencies:
#  flutter_test:
#    sdk: flutter

#dependency_overrides:
#  flutter_svg: 0.20.0-nullsafety.3
#  path_drawing: ^0.5.0-nullsafety.0
#  path_parsing: ^0.2.0-nullsafety

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/logo.png
    - assets/page1.png
    - assets/page2.png
    - assets/page3.png
    - assets/page4.png
    - assets/wave1.png
    - assets/wave2.png
    - assets/wave3.png
    - assets/wave4.png
    - assets/Roboto-Regular.ttf

  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans/GoogleSans-Regular.ttf
        - asset: fonts/GoogleSans/GoogleSans-Bold.ttf
          weight: 700
        - asset: fonts/GoogleSans/GoogleSans-Italic.ttf
          style: italic
        - asset: fonts/GoogleSans/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/GoogleSans/GoogleSans-Medium.ttf
          weight: 500
        - asset: fonts/GoogleSans/GoogleSans-MediumItalic.ttf
          style: italic
          weight: 500

    - family: SpaceMono
      fonts:
        - asset: fonts/SpaceMono/SpaceMono-Regular.ttf
        - asset: fonts/SpaceMono/SpaceMono-Bold.ttf
          weight: 700
        - asset: fonts/SpaceMono/SpaceMono-Italic.ttf
          style: italic
        - asset: fonts/SpaceMono/SpaceMono-BoldItalic.ttf
          weight: 700
          style: italic

    - family: RedHatDisplay
      fonts:
        - asset: fonts/RedHatDisplay/RedHatDisplay-Regular.ttf
        - asset: fonts/RedHatDisplay/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: fonts/RedHatDisplay/RedHatDisplay-Italic.ttf
          style: italic
        - asset: fonts/RedHatDisplay/RedHatDisplay-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/RedHatDisplay/RedHatDisplay-Medium.ttf
          weight: 500
        - asset: fonts/RedHatDisplay/RedHatDisplay-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/RedHatDisplay/RedHatDisplay-Black.ttf
          weight: 800
        - asset: fonts/RedHatDisplay/RedHatDisplay-BlackItalic.ttf
          style: italic
          weight: 800
